version: '3.6'

services:
  onlyoffice:
    image: onlyoffice/documentserver-de
    container_name: onlyoffice
    restart: always
    environment:
      - JWT_SECRET=my_jwt_secret
    ports:
      - "8081:80"
      - "5432:5432"
    volumes:
      - /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
      - /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data   
      - /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice     
      - /app/onlyoffice/DocumentServer/db:/var/lib/postgresql