name: "bind"
services:
  bind:
    image: 172.16.0.197:8083/tool/bind:latest
    container_name: bind
    network_mode: bridge
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "10000:10000/tcp"
    environment:
      WEBMIN_INIT_SSL_ENABLED: false
      ROOT_PASSWORD: root123
    volumes:
      -  /app/bind/data:/srv/docker/bind
