version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      # 挂载数据目录
      - /app/mongdb/db:/data/db
      # 挂载日志目录
      - /app/mongdb/log:/var/log/mongodb
      # 挂载配置目录
      - /app/mongdb/config:/etc/mongo
