version: '3.1'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - 5001:8081
      - 5000:5000
    network_mode: bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/nexus-data:/nexus-data
