name: 'nexus3'
services:
  nexus:
    image: docker.m.daocloud.io/sonatype/nexus3
    container_name: nexus3
    user: root
    ports:
      - 5001:8081
      - 5000:5000
      - 8083:8083
    network_mode: bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/nexus-data:/nexus-data
