name: tdengine
services:
  tdengine:
    image: tdengine/tdengine
    container_name: tdengine
    restart: always
    network_mode: bridge
    ports:
      - "6030:6030"
      - "6031:6031"
      - "6020:6020"
      - "6021:6021"
    volumes:
      - /app/tdengine/data:/var/lib/taos
