services:
  maven11:
    build:
      context: .
      dockerfile: Dockerfile-maven
      args:
        VERSION: 11
    image: 172.16.0.197:8083/tool/docker/mvn-11:1.2
  maven17:
    build:
      context: .
      dockerfile: Dockerfile-maven
      args:
        VERSION: 17
    image: 172.16.0.197:8083/tool/docker/mvn-17:1.1
  maven21:
    build:
      context: .
      dockerfile: Dockerfile-maven
      args:
        VERSION: 21
    image: 172.16.0.197:8083/tool/docker/mvn-21:1.1

  gradle11:
    build:
      context: .
      dockerfile: Dockerfile-gradle
      network: host
      args:
        VERSION: 11
    image: 172.16.0.197:8083/tool/docker/gradle-11:1.1

  gradle17:
    build:
      context: .
      dockerfile: Dockerfile-gradle
      network: host
      args:
        VERSION: 17
    image: 172.16.0.197:8083/tool/docker/gradle-17:1.1

  gradle21:
    build:
      context: .
      dockerfile: Dockerfile-gradle
      network: host
      args:
        VERSION: 21
        GRADLE_VERSION: 8.12.1
    image: 172.16.0.197:8083/tool/docker/gradle-21:1.5.3
  gradle25:
    build:
      context: .
      dockerfile: Dockerfile-gradle-jdk25
      network: host
      args:
        VERSION: 25
        GRADLE_VERSION: 9.1.0
    image: 172.16.0.197:8083/tool/docker/gradle-25:0.2
    container_name: test
