FROM docker:git
LABEL org.opencontainers.image.authors="zqh"
ARG VERSION=11
ARG GRADLE_VERSION=7.6
WORKDIR /app
# 设置阿里云镜像仓库
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk update

# 安装jdk
RUN apk add openjdk$VERSION
# 安装sshpass
RUN apk add sshpass

# 创建目录
RUN mkdir -p /root/.docker/
RUN mkdir /root/.ssh && touch /root/.ssh/known_hosts
COPY id_rsa /root/.ssh/id_rsa
RUN apk add dos2unix
RUN dos2unix /root/.ssh/id_rsa
# Permissions 0755 for '/root/.ssh/id_rsa' are too open
RUN chmod 700 ~/.ssh
RUN chmod 600 /root/.ssh/id_rsa

COPY config.json /root/.docker/config.json

RUN apk add --no-cache bash unzip wget && \
    wget http://172.16.0.227:84/gradle/gradle-${GRADLE_VERSION}-bin.zip -O /tmp/gradle.zip && \
    unzip /tmp/gradle.zip -d /opt && \
    ln -s /opt/gradle-${GRADLE_VERSION} /opt/gradle && \
    rm /tmp/gradle.zip

ENV PATH="/opt/gradle/bin:${PATH}"

RUN apk cache clean
COPY dockerDelete.sh /app/
COPY SpringbootHealthCheck.sh /app/
RUN sed -i 's/\r$//' /app/SpringbootHealthCheck.sh
RUN gradle --version
RUN apk del --no-cache wget dos2unix