ARG DOCKER_VERSION="29.3.1-dind-alpine3.23"
FROM docker:${DOCKER_VERSION}
LABEL org.opencontainers.image.authors="zqh"
ARG VERSION=11
ARG GRADLE_VERSION=7.6
WORKDIR /app
# 设置阿里云镜像仓库
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
# 下载工具
RUN apk update && apk add --no-cache curl tar
# 安装jdk
# 安装jdk
RUN apk add openjdk$VERSION
RUN apk add --no-cache git
# 安装sshpass
RUN apk add sshpass

# 创建目录
RUN mkdir -p /root/.docker/
RUN mkdir /root/.ssh && touch /root/.ssh/known_hosts
COPY id_rsa /root/.ssh/id_rsa
RUN apk add dos2unix
RUN dos2unix /root/.ssh/id_rsa
# Permissions 0755 for '/root/.ssh/id_rsa' are too open
RUN chmod 700 ~/.ssh
RUN chmod 600 /root/.ssh/id_rsa

COPY config.json /root/.docker/config.json

RUN apk add --no-cache bash unzip

RUN curl http://172.16.0.227:84/gradle/gradle-${GRADLE_VERSION}-bin.zip -o /tmp/gradle.zip && \
    unzip /tmp/gradle.zip -d /opt && \
    ln -s /opt/gradle-${GRADLE_VERSION} /opt/gradle && \
    rm /tmp/gradle.zip

ENV PATH="/opt/gradle/bin:${PATH}"

COPY dockerDelete.sh /app/
RUN dos2unix /app/dockerDelete.sh
COPY SpringbootHealthCheck.sh /app/
RUN dos2unix /app/SpringbootHealthCheck.sh

# 验证安装 即使设置了 ENV PATH=...，在 RUN 命令中可能因为使用 /bin/sh 而不加载环境变量。
# RUN source /etc/profile && java -version && gradle --version

RUN apk del --no-cache wget dos2unix

RUN apk cache clean