name: mydumper
services:
  mydumper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydumper
    image: 172.16.0.197:8083/tool/mydumper:1.2
    network_mode: bridge
    environment:
      MYSQL_HOST: 172.16.0.170
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: sGEbmrHsU4;H
      MYSQL_DATABASE: ry_vue
    restart: unless-stopped
    volumes:
      - D:/E/运维/testBackup:/backup
