FROM alpine:3.20

# 设置阿里云镜像仓库
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
ENV TimeZone=Asia/Shanghai
RUN ln -sf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone
# 安装jdk21
RUN apk add --no-cache openjdk21
# 安装必要的软件包以及依赖 字体
RUN apk update && apk add --no-cache fontconfig ttf-dejavu
# 删除缓存
RUN rm -rf /var/cache/apk/* && rm -rf /tmp/*