name: mongodb
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    network_mode: bridge
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      # 挂载数据目录: /data/db/.mongodb/mongosh 目录里面包含日志文件
      - ./db:/data/db
      - ./configdb:/data/configdb
