name: 'mongodb'
services:
  mongodb:
    image: 172.16.0.197:8083/mongo:8.0.13-rc2
    container_name: mongodb
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "27018:27017"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./data:/data/db
      - ./log/primary:/var/log/mongodb
    command: /bin/sh -c "
      mkdir -p /data/mongodb &&
      echo 'fXhGqBe5QOH/KnPH+6A2Pn5561NBBZsRR+jc+5ZlF5LoHw4hM2FMqmGu4xNumWZt
      buSBzaEI+rWmorelNwFXjgYv9sl2bVHNnDBU3wFM6aDnpLm5nTe/sXxTpXONMl2G
      71+ewEl35KVwmafoLQ+flklCXe8b0oftISDmryJ9DE+FLjNAPHgRv5E23pPsmT6+
      s39vwM938hLhDXYi6rqsHd5YTf2zjRiGeRevxsRTh9La6F9ZqcSA7q1TbZULYeoG
      3JX6cDh9tGoH+wYXD0sYxpyHgwOprHlLPg2dzpeEotnJgThX3KIHUMEqZoHvqMmt
      DgORQu9OJWGQ4Aa9TI4QdFEESSzqF12EG3eHTqBW0AP/POyVLEySNvEbd3hgbdxy
      1bGt7f6qKa149VjyMDwSIG8tX+XBLwhO/HpWV6mTLbmJaeNxSr0j0teddbhyu18s
      3XmndgIRZmQ6fUTJV9TZuQwS/HPf5H5Sm3tqY5ElX5+0s+ZStZQM34xiDdk8VlYX
      37vphLEJ57sLqXXg+JSuWe3HU96P555QnQNEECcK86f9abIZG8lvjE5kr7NUzXnK
      bAr2061e1OG5TtOwCP/pS7o/dSD4WrC0L6kAAtw++B2Ayqh5eGFYmQvfkrDnwpv1
      0W0Ob/fvjIyilF0ugMAVCPbenQLprSfDDLA+2aZzSr96AcW0VwLhFjBWJiehyp3N
      e713zP7SHEbpD0GnTy2Z3onqNxqscwMmY+Oc1zJfs5rvDkFZDS1TcQJmPGctRpFr
      4TUCQqN+SIyVRHATPtPHllwKkymuGVBraOmhhflEkzpKh47oXWEdA4luaBVmSd2X
      S2ZXWsPtB369Jrx48ibGq0gxF9r65k7NqB12Pz5nc1Cope0rF4+DPJ/PCh913rh0
      PRJESmqIcO7WRp19+/RW1O98pjHDqdmVsbgdOlSK5P/x/zqKqRKGwXaiiIsI4RDg
      hLaa1mmXQVwxSL8JGaCZwWBmzyGvhIlb2qRTWJdLU+R8m8u0
      ' > /data/mongodb/keyFile.pem &&
      chmod 600 /data/mongodb/keyFile.pem &&
      chown mongodb:mongodb /data/mongodb/keyFile.pem &&
      mongod \
      --replSet rs0 \
      --bind_ip_all \
      --clusterAuthMode keyFile \
      --keyFile /data/mongodb/keyFile.pem \
      --logpath /var/log/mongodb/mongod.log \
      --logappend \
      --auth
      "

# 1、准备keyFile
# 测试在4.x版本不需要使用keyFile,但是≥5.x版本是必须要KeyFile的，不然会报 “BadValue: security.keyFile is required when authorization is enabled with replica sets”
# 1、1 openssl rand -base64 128 > ./mongodb/keyFile
#  openssl rand -base64 756 > keyFile
# 1.2 keyFile文件的权限必须为600,如果权限太大，启动时会报“error opening file: /data/mongodb/keyFile: bad file”
#     sudo chmod 600 keyFile
# 1.3 需要把keyFile文件的所属用户和用户组改为mongodb不然在启动时会报"permissions on /data/mongodb/keyFile are too open"
#     sudo chown mongod:mongod keyFile

#2、进入容器创建root用户  docker exec -it mongodb mongosh
# 在 MongoDB 控制台中执行以下命令, 创建了一个一主一从的 MongoDB
#   如果是一个副本集那么 rs.initiate() 命令即可
#    rs.initiate({_id: "rs0", members: [{ _id : 0, host : "172.16.0.15:27017" }, { _id : 1, host : "172.16.0.15:27018" }]}))
# 或者使用 容器名称
#    rs.initiate({_id: "rs0", members: [{_id: 0, host: "mongodb_primary:27017"}, {_id: 1, host: "mongodb_secondary:27018"}]})


# 3、设置用户密码
#    副本集镜像设置用户密码失败也是说环境
#  mongosh
#   use admin
#   db.createUser({user: "admin", pwd: "123456", roles:[{role: "root", db: "admin"}]});
#


#  echo "vm.max_map_count=262144" > /etc/sysctl.conf
#  sysctl -p

# 授权登录
# use admin
# db.auth("admin", "123456")
