version: "3.8"

services:
  mongodb_primary:
    image: mongo
    container_name: mongodb_primary
    ports:
      - "27017:27017"
    volumes:
      - /app/mongodb/primary_data:/data/db
    command: mongod --replSet rs0
    networks:
      - mongo-cluster

  mongodb_secondary:
    image: mongo
    container_name: mongodb_secondary
    ports:
      - "27018:27017"
    volumes:
      - /app/mongodb/secondary_data:/data/db
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge

#docker exec -it mongodb_primary mongo
# 在 MongoDB 控制台中执行以下命令, 创建了一个一主一从的 MongoDB 副本集
#rs.initiate({_id: "rs0", members: [{ _id : 0, host : "mongodb_primary:27017" }, { _id : 1, host : "mongodb_secondary:27017" }]})
