FROM ubuntu:24.04

# 设置非交互式安装（避免 tzdata 弹窗）
ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i 's/http:\/\/archive.ubuntu.com/https:\/\/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && sed -i 's/# deb/deb/g' /etc/apt/sources.list

RUN apt-get clean && apt-get update \
    && apt-get install -y locales language-pack-zh-hans \
    && localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8 \
    && locale-gen zh_CN.UTF-8 \
    && apt-get install -y tzdata  \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  \
    && apt-get install -y fontconfig ttf-mscorefonts-installer ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy

# 安装jdk
RUN apt-get install -y openjdk-21-jdk

# 安装libreoffice
RUN apt-get install -y libxrender1 libxinerama1 libxt6 libxext-dev libfreetype6-dev libcairo2 libcups2 libx11-xcb1 libnss3
RUN apt-get install -y libreoffice

#RUN wget https://kkfileview.keking.cn/LibreOffice_7.3.7_Linux_x86-64_deb.tar.gz -cO libreoffice_deb.tar.gz  \
#    && tar -zxf /tmp/libreoffice_deb.tar.gz  \
#    && cd /tmp/LibreOffice_7.3.7.2_Linux_x86-64_deb/DEBS  \
#    && dpkg -i *.deb  \
#    && rm -rf /tmp/*  \
#    && rm -rf /var/lib/apt/lists/*

RUN mkfontscale  \
    && mkfontdir  \
    && fc-cache -fv

RUN apt-get clean && \
        rm -rf /var/lib/apt/lists/*

ENV LANG=zh_CN.UTF-8
ENV LC_ALL=zh_CN.UTF-8

ADD kkFileView-*.tar.gz /opt/

ENV KKFILEVIEW_BIN_FOLDER=/opt/kkFileView-4.4.0/bin

ENTRYPOINT ["java","-Dfile.encoding=UTF-8",\
    "-Dspring.config.location=/opt/kkFileView-4.4.0/config/application.properties",\
    "-jar","/opt/kkFileView-4.4.0/bin/kkFileView-4.4.0.jar"]