name: postgresql
services:
  db:
    image: postgres:14
    container_name: 'postgresql'
    restart: always
    network_mode: bridge
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: ePVw#DD#q
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
