version: "3.8"

services:
  jtjc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_VERSION: ${PROJECT_VERSION:-1.0.0}
        PORT: ${PORT:-8605}
        DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
    image: ${IMAGE_FULL_NAME}
    container_name: ${CONTAINER_NAME:-stc-jtjc}-${PROJECT_VERSION-1.0.0}
    restart: always
    network_mode: bridge
    ports:
      - ${PORT:-8605}:8605
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILES_ACTIVE:-dev}
      TZ: Asia/Shanghai
    volumes:
      # 挂载日志目录
      - /app/logs/${CONTAINER_NAME:-stc-jtjc}:/app/logs
