-- 创建172，192 内网访问授权的用户
CREATE USER  'stcjc'@'172.%' IDENTIFIED BY 'xxxx';
CREATE USER  'stcjc'@'192.%' IDENTIFIED BY 'xxxx';

-- 授权，除了创建数据库与删除数据库和授予其他用户的权限，其他权限全部授权
GRANT 	SELECT,	INSERT,	UPDATE,	DELETE,
CREATE,	ALTER,	DROP,	INDEX,	LOCK TABLES,
	REFERENCES,	CREATE ROUTINE,	ALTER ROUTINE,
	EXECUTE,	TRIGGER,	EVENT
ON `stcjc`.* TO 'stcjc'@'172.%';

GRANT 	SELECT,	INSERT,	UPDATE,	DELETE,
CREATE,	ALTER,	DROP,	INDEX,	LOCK TABLES,
	REFERENCES,	CREATE ROUTINE,	ALTER ROUTINE,
	EXECUTE,	TRIGGER,	EVENT
ON `stcjc`.* TO 'stcjc'@'192.%';


-- 刷新权限
FLUSH PRIVILEGES;

-- 查看指定用户的所有权限
SHOW GRANTS FOR 'stcjc'@'192.%';
SHOW GRANTS FOR 'stcjc'@'172.%';