version: "3.6"

services:
  db:
    image: postgres:14
    container_name: 'postgresql'
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: ePVw#DD#q
    ports:
      - "5432:5432"
    volumes:
      - /app/postgresql/data:/var/lib/postgresql/data
