FROM alpine:latest
LABEL maintainer="zqh"

# 替换阿里云仓库
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

# 更新系统并安装必要的依赖项
RUN apk update && apk add --no-cache \
    bash \
    build-base \
    ca-certificates \
    curl \
    zip \
    zlib-dev
	
ENV TimeZone='Asia/Shanghai'

# 设置时区
RUN ln -sf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

RUN apk add --no-cache openjdk17

ADD simsun.ttc /usr/share/fonts/
ADD simsun.ttf /usr/share/fonts/
ADD simhei.ttf /usr/share/fonts/
# ADD 仿宋_GB2312.ttf /usr/share/fonts/
ADD Times_New_Roman.ttf /usr/share/fonts/

# 设置工作目录
WORKDIR /app

# 容器启动命令
CMD ["bash"]