services:
  ui:
    image: flowable/flowable-ui:6.8.0
    container_name: flowable-ui
    ports:
      - "8080:8080"

  admin:
    image: flowable/flowable-admin:6.5.0
    container_name: flowable-admin
    ports:
      - "9988:9988"
    environment:
      SERVER_PORT: 9988
      SERVER_CONTEXT_PATH: /flowable-admin
      SERVER_HOST: ${host_ip:-172.16.0.170}
      FLOWABLE_COMMON_APP_IDM-URL: http://${host_ip:-172.16.0.170}:8080/flowable-ui/idm/#/login
      FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
      FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
      # 当用户未登录访问 Admin 控制台时，会被重定向到这个地址进行认证
      FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://${host_ip:-172.16.0.170}:8080/flowable-ui/idm/#/login
      # 数据库连接配置  com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.16.0.197:5432/flowable
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ePVw#DD#q
      # 流程引擎（Process Engine）连接配置：组合后地址 http://<host>:9977/flowable-rest/service
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS: http://172.16.0.170
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT: 8080
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT: /flowable-ui
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT: process-api
      # 配置 Flowable CMMN 引擎的 REST 接口地址 Case Management事件管理
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS: http://172.16.0.170
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT: 8080
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT: /flowable-ui
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT: cmmn-api
      # DMN 引擎连接配置（决策模型）
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS: http://172.16.0.170
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT: 8080
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT: /flowable-ui
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT: dmn-api
      # Form 引擎连接配置（表单服务）
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS: http://172.16.0.170
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT: 8080
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT: /flowable-ui
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT: form-api
      # Content 引擎连接配置（内容服务）
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS: http://172.16.0.170
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT: 8080
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT: /flowable-ui
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT: content-api
      # App 引擎连接配置（应用服务）
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_SERVER-ADDRESS: http://172.16.0.170
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_PORT: 8080
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_CONTEXT-ROOT: flowable-rest
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_REST-ROOT: app-api
