name: minio

services:
  minio:
    image: minio/minio
    container_name: minio
    command: "server /data --console-address \":9001\""
    network_mode: bridge
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data

 # 教程：https://mp.weixin.qq.com/s/qHjOEeQ3CaA0U4a2YBi3Pw?
