(function () {
  // 1. 提取所有资源 URL（去重）
  const entries = performance.getEntriesByType("resource");
  const urls = [...new Set(entries.map(r => r.name))].filter(url =>
    (url.startsWith('http') || url.startsWith('https')) && !url.includes('chrome-extension')
  ).filter((v, i, a) => a.indexOf(v) === i); // 去重;

  if (urls.length === 0) {
    alert('❌ 未找到任何有效的 HTTP/HTTPS 资源。\n请确保在 Network 面板开启状态下刷新页面后再运行此脚本。');
    return;
  }

  // 2. XML 转义函数
  function escapeXml(unsafe) {
    if (typeof unsafe !== 'string') return '';
    return unsafe
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&apos;");
  }

  // 3. 生成 JMeter XML 片段
  let xmlOutput = '<!-- Generated by Browser-to-JMeter Script -->\n';

  urls.forEach((fullUrl, index) => {
    try {
      const urlObj = new URL(fullUrl);
      const protocol = urlObj.protocol.replace(':', '');
      const host = urlObj.hostname;
      const port = urlObj.port || (protocol === 'https' ? '443' : '80');
      const pathWithQuery = urlObj.pathname + (urlObj.search || '');

      xmlOutput += `
  <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="${urlObj.pathname}" enabled="true">
    <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" enabled="true"/>
    <stringProp name="HTTPSampler.domain">${escapeXml(host)}</stringProp>
    <stringProp name="HTTPSampler.port">${port}</stringProp>
    <stringProp name="HTTPSampler.protocol">${protocol}</stringProp>
    <stringProp name="HTTPSampler.path">${escapeXml(pathWithQuery)}</stringProp>
    <stringProp name="HTTPSampler.method">GET</stringProp>
    <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
    <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
    <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
    <boolProp name="HTTPSampler.postBodyRaw">false</boolProp>
  </HTTPSamplerProxy>
  <hashTree/>`;
    } catch (e) {
      console.warn('Invalid URL skipped:', fullUrl);
    }
  });

  // 4. 复制到剪贴板
  copy(xmlOutput); // 自动复制到剪贴板（仅限 Chrome）
})();