version: '3.6'
services:
    redis:
        image: redis:latest
        container_name: redis
        privileged: true
        restart: always
        ports:
            - 6379:6379
        environment: 
            TZ: "Asia/Shanghai"
        command:
            -- requirepass "pNlisJTYYf4"
            -- bind "0.0.0.0"
            -- protected-mode "no"
            -- appendonly "yes"
            -- databases 5
            #-- aclfile "/etc/redis/users.acl"
        volumes:
            - ./data:/data
            #- ./aclfile:/etc/redis/users.acl
           
